### PR TITLE
fix: fix typo

### PR DESCRIPTION
**Pull request by jsantos42**
## Summary by CodeRabbit

- **Documentation**
  - Corrected a typo in the "Getting Started" section of the homepage, changing "precide" to "precise" for clarity in the "Resume Suggestions" content.

### CODE REVIEW

**Comment by levino** [comment]
Hi @jsantos42, I do not understand your question. Could you please elaborate?

**Review by levino — APPROVED** [review]
Thank you for catching this.

**Comment by jsantos42** [comment]
> Now we just have to accept and merge it, right? 
I believed so, yes!

> Did you want to ask whether or not you should open the PR from a different branch than "master"?

Precisely

> Thank you for catching this.

You're welcome! Thank you guys for this awesome project

**Comment by jsantos42** [comment]
Hi @levino 👋

> > Now we just have to accept and merge it, right?
> 
> I believed so, yes!
> 
> > Did you want to ask whether or not you should open the PR from a different branch than "master"?
> 
> Precisely
> 
> > Thank you for catching this.
> 
> You're welcome! Thank you guys for this awesome project

**Comment by levino** [comment]
This is what I think I understand about forking and PRs: It does not matter how you call a branch on a fork. If you would push to this repo, you should use a name other than `master` for obvious reasons 😄 (It is impossible to push to `master` btw since this branch is protected in this repo). When we merge, we merge the new commits in your branch, not your branch. The branch does not exist outside the scope of your fork so to say. I hope that helps. Cheers.

**Comment by thomasdavis** [comment]
@jsantos42 thanks Jaoa, you did it correctly! as above, because it is from your own repo, you can use the same branch name. though I would recommend you give it a different name when creating pull requests upstream

**Pull request merged**
