### PR TITLE
remove part of the "global install crap"

### PR DESCRIPTION
**Pull request by levino**
also updates the README with the new usage

### CODE REVIEW

**Comment by levino** [comment]
Thanks for the invite @thomasdavis ! I still cannot authorize the registry deployment. I can however merge this PR with the check failing. I think we should protect `master` better and disallow merging of PRs with failing checks.

**Comment by thomasdavis** [comment]
> Thanks for the invite @thomasdavis ! I still cannot authorize the registry deployment. I can however merge this PR with the check failing. I think we should protect `master` better and disallow merging of PRs with failing checks.

What is your vercel email?

**Comment by levino** [comment]
> What is your vercel email?

Looks like you found it :)

**Comment by levino** [comment]
If you do not object, I will go ahead and merge. But we could also agree on giving a thumbs up in form of an approving review or something. Might even enforce it as a github branch protection rule. I usually do that.

**Comment by thomasdavis** [comment]
You can just merge liberally for now. As long as nothing breaks.

**Pull request merged**
