### PR TITLE
fix: add a link to a github issue when themes are missing

### LINKED ISSUE #38: enable users to ask for support of specific themes
Users might get errors when trying to render resumes with deprecated / removed themes. Currently they get a misleading error message, claiming that they mistyped their username but actually they just have to use another theme. We need to handle the missing theme error appropriately and show a useful error message.

A solution was proposed in #37 in combination with #36.

### PR DESCRIPTION
**Pull request by thomasdavis**
Fix #38 

## Summary by CodeRabbit

- **Bug Fixes**
  - Corrected typo in error messages to accurately reflect "not supported formatter."
  - Improved error handling for missing themes with informative messages and resource links.
  - Updated HTTP status codes for specific errors to enhance API response accuracy.

- **Documentation**
  - Clarified that there are no changes to function signatures or global structures.

### CODE REVIEW

**Comment by thomasdavis** [comment]
@levino approval on this one is kinda of urgent

**Comment by levino** [comment]
Please see https://github.com/jsonresume/jsonresume.org/issues/38#issuecomment-1831578943 If you get impatient, let me know and I will approve anyhow.

**Comment by levino** [comment]
@thomasdavis You can now "override" the branch protection rules and merge as you please. There should be a checkbox with a red warning text just above the "merge button". This is so you do not become blocked if I am absent etc.

**Comment by levino** [comment]
I would also add a test to try to open the site with a non-working theme and see that it returns an error code and check that the message contains expected strings (like "github issue" or something).

**Comment by thomasdavis** [comment]
@levino good feedback. just merging for now so i can collect the errors of the themes that are missing. but will add the test, and move to a theme request template later today

**Pull request merged**
