### PR TITLE
reworking how template rendering works

### PR DESCRIPTION
**Pull request by thomasdavis**
mostly just to support `fs` again. (which took way too long to figure out)

but the abstractions will make more sense nontheless

not ready for review: pr'ing to show the line of thinking

- [ ] move all `lib` like functionality out of the api folder 
- [ ] the api should serve all extension behavior .js, .html and the template rendering served as a component
- [ ] remove locally cloned themes, now that `fs` works again 
- [ ] change docs to remove the idea of `fs` anyway (find relevant issue where @levino made a good point that it shouldn't be possible)

### CODE REVIEW

**Comment by thomasdavis** [comment]
got stuck on this https://github.com/vercel/next.js/discussions/17269 
-1 nextjs

**Comment by levino** [comment]
What kind of URLs would you like to prerender?

**Comment by levino** [comment]
I just saw: You are using the `pages` router which is outdated. I suggest to use exclusively the [`app` router](https://nextjs.org/docs#app-router-vs-pages-router). Then there also is no `getStaticProps`.

Even if you are using `getStaticProps` you cannot possibly want to generate a page for each possible username and theme. I think you should just server side render these pages.

**Comment by levino** [comment]
With the app router you can access the [`searchParams` prop](https://nextjs.org/docs/app/api-reference/file-conventions/page) in the render function.

**Comment by thomasdavis** [comment]
Moving to the `app` router makes sense. I will migrate it all there tomorrow.

Been trying to furiously refactor code because I have some spare time at the moment. 

The end goal of this PR is to get the registry template rendering working inside of `pages/` and then any extensions for `resume.json`, `resume.yaml` etc outputted in the `api` folder. 

Which allows the templates to use nodejs libraries such as `fs`, and then to logically move pure functional `lib` like functions outside of the api folder.

**Comment by levino** [comment]
With next.js you are in serverless / lambda land. There is no file system. Using `fs` will never work properly because the code will be bundled and the bundler does not understand that the files which you will later load via `fs` are to be bundled as well. My recommendation: Just drop support for all the templates which use `fs` under the hood. I think this will never work properly.

**Comment by thomasdavis** [comment]
feel free to commit any code you want to my pr's, it don't bother me, i'm sure we both have adequate git-fu

**Comment by thomasdavis** [comment]
I know we've talked about the `fs` support before, and I lean towards what your thinking. Will share my reflections tomorrow.

**Comment by levino** [comment]
It is a question of requirements. I cannot decide that for you. I am just saying you would make your life easier if you lowered the bar. If I can be of help with some code, let me know and I will see what I can do, but I will not support `fs`. It is just too painful imo.

**Comment by levino** [comment]
#58 is related

**Comment by thomasdavis** [comment]
Closing in favor of https://github.com/jsonresume/jsonresume.org/issues/58

**Pull request closed without merging**
