### PR TITLE
Feature/improve stackoverflow theme integration

### PR DESCRIPTION
**Pull request by levino**
## Summary by CodeRabbit

- **New Features**
  - Implemented a new ESLint configuration for improved code quality.
  - Added GitHub Actions workflow updates including Node.js version bump and Slack notifications for releases.
  - Introduced Storybook configuration enhancements for better component documentation.
  - Launched internationalization support with `i18next` for Storybook.
  - Created new React components for displaying various sections of a resume, such as `Awards`, `Certificates`, `Education`, `Interests`, `Languages`, `Projects`, `Publications`, `References`, and `Skills`.
  - Added Storybook stories for newly created components to visualize component states.
  - Updated theme README with information about the new `jsonresume-theme-stackoverflow-react`.
  - Enhanced CSS styling for better visual presentation across devices.

- **Bug Fixes**
  - Addressed design regressions and improved layout consistency.
  - Fixed issues with file reduction for npm publication.

- **Documentation**
  - Updated CHANGELOG with recent updates, bug fixes, and new features.
  - Improved documentation for the new theme and its usage.

- **Refactor**
  - Streamlined components and stories for better modularity and maintainability.

- **Style**
  - Applied comprehensive style updates to ensure a modern and responsive design.

- **Chores**
  - Adjusted `.gitignore` and `.npmignore` configurations for cleaner repository management.
  - Updated `.yarnrc.yml` for Yarn configuration consistency.

- **Tests**
  - Added basic test configurations for CI.

Please note that internal code-level details are intentionally omitted to maintain confidentiality.

### CODE REVIEW

**Review by thomasdavis — APPROVED** [review]

**Comment by levino** [comment]
@thomasdavis Please only approve "Ready for review" PRs. I really hope you take a look, once I have finished the PRs because it is always better to have 4 eyes on the things in order not to break stuff or change things that I did not intend to. I might even split this PR up because it is becoming huge and a bit messed about the scope.

**Comment by thomasdavis** [comment]
No worries, I did have a look at it all. p.s. love it. will wait for "ready for review" next time

**Comment by levino** [comment]
I will try to clean up the git history. Also I want to enable deployment to npm from ci, so I do not have to do it by hand.

**Comment by thomasdavis** [comment]
oh npm deployment would be hot. trigged by package.json version changes or something else?

**Comment by levino** [comment]
Merging. Any fallout from this I will mop up later.

**Comment by thomasdavis** [comment]
@levino so good to have the stackoverflow theme back, great job

**Pull request merged**
